AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CalendaruiEventsService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "calendar-ui-events-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        AllowOrigin: "'http://localhost:5173'" # replace with frontend app URL

  CalendaruiEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendaruiEventsTable
      Events:
        EventsOptions:
          Type: Api
          Properties:
            Path: /events
            Method: OPTIONS
            RestApiId: !Ref CalendaruiEventsService
        GetEvent:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: GET
            RestApiId: !Ref CalendaruiEventsService
        GetEvents:
          Type: Api
          Properties:
            Path: /events
            Method: GET
            RestApiId: !Ref CalendaruiEventsService
        PutEvent:
          Type: Api
          Properties:
            Path: /events
            Method: POST
            RestApiId: !Ref CalendaruiEventsService
        DeleteEvent:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: DELETE
            RestApiId: !Ref CalendaruiEventsService
        UpdateEvent:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: PUT
            RestApiId: !Ref CalendaruiEventsService
    Metadata:
      BuildMethod: makefile

  CalendaruiEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CalendaruiEvents
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
